name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Setup Flutter
      uses: subosito/flutter-action@v2.12.0
      with:
        channel: 'stable'
        flutter-version: '3.27.1'

    - name: Build Web
      run: flutter build web --base-href /portfolio/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.WEB_DEPLOY_SECRET_KEY }}
        publish_dir: ./build/web