name: Deploy to GitHub Pages

env:
  CUSTOM_DOMAIN: jaehoon-portfolio.com
  GITHUB_REPO: https://github.com/bluekmky1/portfolio.git

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1

    - name: Setup Flutter
      uses: subosito/flutter-action@v2.12.0
      with:
        channel: 'stable'
        flutter-version: '3.27.1'

    - name: Build Web
      run: flutter build web --release

    - name: Set custom domain
      run: echo "jaehoon-portfolio.com" > build/web/CNAME

    - name: Deploy to GitHub Pages
      run: cd build/web && git init && \
           git add . && \
           git commit -m "Deploy to GitHub Pages" && \
           git branch -M gh-pages && \
           git remote add origin ${{ env.GITHUB_REPO }} && \
           git push -u --force origin gh-pages